[package]
name = "sonic-csv"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.7.3"
rand_chacha = "0.3.1"

[[bench]]
name = "basic"
harness = false